exports.defaultCards = [
	{
		name: "Barrage",
		character: "Gravity Girl",
		type: "Action",
		utilityValues: [""],
		text: "Throw. Deal 2 damage to target opponent. If you've thrown twice this turn, deal 4 damage instead.",
		flavor: ["Didn't you learn the first time?"],
		illustrations: ["../../public/images/gg-barrage.png"],
		rating: [""],		
		tags: ["aggressive", "player damage", "throw"],
		comments: ["Aggressive - JM"]
	},
	{
		name: "Chain Reactions",
		character: "Gravity Girl",
		type: "Utility",
		utilityValues: ["2","3","0"],
		text: "When this is destroyed, each player discards two cards.",
		flavor: ["I haven't cleaned up yet. Watch your step."],
		illustrations: ["../../public/images/gg-chainreactions.png"],
		rating: [""],
		tags: ["disruption", "discard"],
		comments: ["Solid stats and disruption - JM"]
	},
	{
		name: "Controlled Ricochet",
		character: "Gravity Girl",
		type: "Action",
		utilityValues: [""],
		text: "Whenever a Utility is destroyed this turn, you may draw a card.",
		flavor: ["Angles. Corners. I love geometry."],
		illustrations: ["../../public/images/gg-controlledricochet.png"],
		rating: [""],
		tags: ["combo", "card draw"],
		comments: ["Can get 3-4 cards consistently - JM"]
	}, 
	{
		name: "Distraction",
		character: "Gravity Girl",
		type: "Action",
		utilityValues: [""],
		text: "Throw. Shuffle your hand into your deck and draw 2 cards.",
		flavor: ["Time to regroup."],
		illustrations: ["../../public/images/gg-distraction.png"],
		rating: [""],
		tags: ["versatile", "card draw", "throw"],
		comments: ["Swiss army knife: healing, card selection, throw trigger - JM"]
	},
	{
		name: "Dreams Of Space",
		character: "Gravity Girl",
		type: "Action",
		utilityValues: [""],
		text: "Discard your hand, then draw 3 cards.",
		flavor: ["I return there in quiet moments."],
		illustrations: ["../../public/images/gg-dreamsofspace.png"],
		rating: [""],
		tags: ["versatile", "card draw"],
		comments: ["Very good card draw for this deck. - JM"]
	},
	{
		name: "Field Of Debris",
		character: "Gravity Girl",
		type: "Action",
		utilityValues: [""],
		text: "Throw. Target Utility gets +1 armor for each Utility destroyed this turn.",
		flavor: ["A personal gravity field. Cool, huh?"],
		illustrations: ["../../public/images/gg-fieldofdebris.png"],
		rating: [""],
		tags: ["defensive", "armor", "throw"],
		comments: ["Flagged as weak, not worth it unless you are getting 4+ armor. - JM"]
	},
		{
		name: "Improvised Barrier",
		character: "Gravity Girl",
		type: "Utility",
		utilityValues: ["3","0","7"],
		text: "When you play this, destroy one of your Utilities.",
		flavor: ["AAAAAAARGGGGGGH! I loved that truck."],
		illustrations: ["../../public/images/gg-improvisedbarrier.png"],
		rating: [""],
		tags: ["defensive", "armor"],
		comments: ["Utility destruction trigger and provides decent armor. Somewhat fragile. - JM"]
	},
	{
		name: "Javelin Throw",
		character: "Gravity Girl",
		type: "Action",
		utilityValues: [""],
		text: "Throw. Deal 4 damage to target Utility.",
		flavor: ["High school track. First in state."],
		illustrations: ["../../public/images/gg-javelinthrow.png"],
		rating: [""],
		tags: ["aggressive", "utility damage", "throw"],
		comments: ["All-purpose Utility removal. - JM"]
	},
	{
		name: "Locked In Combat",
		character: "Gravity Girl",
		type: "Utility",
		utilityValues: ["4","0","4"],
		text: "At the beginning of your turn, you may discard a card. If you do, deal 2 damage to any target.",
		flavor: ["You aren't going anywhere."],
		illustrations: ["../../public/images/gg-lockedincombat.png"],
		rating: [""],
		tags: ["versatile", "damage"],
		comments: ["Not as aggressive as it looks, but very playable in defensive builds. Good armor too. - JM"]
	},
	{
		name: "Maple Tree",
		character: "Gravity Girl",
		type: "Utility",
		utilityValues: ["1","3","0"],
		text: "When you play this, draw a card.",
		flavor: ["This gives me an idea..."],
		illustrations: ["../../public/images/gg-mapletree.png"],
		rating: [""],
		tags: ["aggressive", "card draw"],
		comments: ["All-star. Solid as a rock. - JM"]
	},
	{
		name: "Maximized Momentum",
		character: "Gravity Girl",
		type: "Action",
		utilityValues: [""],
		text: "Throw. Deal damage to any target equal to the thrown Utility's fight value.",
		flavor: ["It's not about speed. It's velocity."],
		illustrations: ["../../public/images/gg-maximizedmomentum.png"],
		rating: [""],
		tags: ["versatile", "damage", "throw"],
		comments: ["Better than it reads. Flexible too. - JM"]
	},
	{
		name: "Motorcycle",
		character: "Gravity Girl",
		type: "Utility",
		utilityValues: ["3","1","2"],
		text: "When you play this, target Utility gets +2 fight this turn.",
		flavor: ["It's not my fault this is our last bike. Now duck!"],
		illustrations: ["../../public/images/gg-motorcycle.png"],
		rating: [""],
		tags: ["aggressive", "fight"],
		comments: ["Good in an aggressive build and great throw target. - JM"]
	},
	{
		name: "Obliterate",
		character: "Gravity Girl",
		type: "Action",
		utilityValues: [""],
		text: "Throw. Deal 3 damage to target Utility. If that destroys it, deal 3 damage to its owner.",
		flavor: ["You can count your splinters in jail."],
		illustrations: ["../../public/images/gg-obliterate.png"],
		rating: [""],
		tags: ["aggressive", "utility damage", "throw"],
		comments: ["Doesn't get rid of big combo cards, but great otherwise. - JM"]
	},
	{
		name: "Picnic Table",
		character: "Gravity Girl",
		type: "Utility",
		utilityValues: ["3","0","0"],
		text: "When this is destroyed, deal 3 damage to target opponent.",
		flavor: ["Sorry about your tablecloth, folks."],
		illustrations: ["../../public/images/gg-picnictable.png"],
		rating: [""],
		tags: ["aggressive", "player damage"],
		comments: ["Aggressive builds only. Largely useless otherwise. - JM"]
	},
	{
		name: "Pile Of Rubble",
		character: "Gravity Girl",
		type: "Utility",
		utilityValues: ["4","0","1"],
		text: "When you play this, draw a card. When this is destroyed, each opponent discards a card.",
		flavor: ["This should buy me some time."],
		illustrations: ["../../public/images/gg-barrage.png"],
		rating: [""],
		tags: ["combo", "card draw"],
		comments: ["Good combo card. Great throw target. - JM"]
	},
	{
		name: "Repurpose",
		character: "Gravity Girl",
		type: "Action",
		utilityValues: [""],
		text: "Throw. Draw 2 cards.",
		flavor: ["Time to put on our thinking caps."],
		illustrations: ["../../public/images/gg-repurpose.png"],
		rating: [""],
		tags: ["versatile", "card draw", "throw"],
		comments: ["GG is short enough on drawing, this helps. Not amazing. - JM"]
	},
	{
		name: "Shrapnel Storm",
		character: "Gravity Girl",
		type: "Action",
		utilityValues: [""],
		text: "Whenever a Utility is destroyed this turn, deal 2 damage to each opponent.",
		flavor: ["Take shelter."],
		illustrations: ["../../public/images/gg-shrapnelstorm.png"],
		rating: [""],
		tags: ["combo", "player damage"],
		comments: ["Huge combo piece. Highest dmg in playtests so far is 18. - JM"]
	},
	{
		name: "Stop Sign",
		character: "Gravity Girl",
		type: "Utility",
		utilityValues: ["3", "2", "0"],
		text: "",
		flavor: ["Can't you read this? Let me show you up close."],
		illustrations: ["../../public/images/gg-stopsign.png"],
		rating: [""],
		tags: ["versatile", "aggressive"],
		comments: ["Solid stats. Good early game but relatively weak late game. - JM"]
	},
	{
		name: "Swirling Vacuum",
		character: "Gravity Girl",
		type: "Action",
		utilityValues: [""],
		text: "Return each of your Utilities to your hand. You may play any number of Utilities this turn..",
		flavor: ["What goes up must come down."],
		illustrations: ["../../public/images/gg-swirlingvacuum.png"],
		rating: [""],
		tags: ["combo", "build-around"],
		comments: ["Very powerful and centerpiece of GG combo deck. - JM"]
	},
	{
		name: "The Team's New Truck",
		character: "Gravity Girl",
		type: "Utility",
		utilityValues: ["3","2","0"],
		text: "When this is destroyed, deal 2 damage to target opponent and each of their Utilities.",
		flavor: ["C'mon! These seats are brand new!"],
		illustrations: ["../../public/images/gg-theteamsnewtruck.png"],
		rating: [""],
		tags: ["aggressive", "damage"],
		comments: ["Extremely powerful. Shrapnel Storm's best friend. - JM"]
	},
	{
		name: "Thrown Into A Portal",
		character: "Gravity Girl",
		type: "Action",
		utilityValues: [""],
		text: "Throw. Place target Utility on top of its owner's deck.",
		flavor: ["Today feels like a beach day."],
		illustrations: ["../../public/images/gg-thrownintoaportal.png"],
		rating: [""],
		tags: ["versatile", "utility damage", "throw"],
		comments: ["Portal + any damage = destroys anything. - JM"]
	},
	{
		name: "Basalt",
		character: "Gravity Girl",
		type: "Crossover",
		utilityValues: ["3","3","0"],
		text: "When you play this, each of your Utilities gets +2 armor.",
		flavor: ["Burly Bartender Taking Back The Streets"],
		illustrations: ["../../public/images/cross-basalt.png"],
		rating: [""],
		tags: ["versatile", "armor", "crossover"],
		comments: ["Very versatile Crossover. All-purpose armor and good stats. - JM"]
	},
	{
		name: "Dark Blades",
		character: "Gravity Girl",
		type: "Crossover",
		utilityValues: ["1","2","0"],
		text: "When this is destroyed, each opponent destroys one of their Utilities. Their choice.",
		flavor: ["The World's Most Dangerous Edgelord"],
		illustrations: ["../../public/images/cross-basalt.png"],
		rating: [""],
		tags: ["aggressive", "utility damage", "crossover"],
		comments: ["If you can get rid of him consistently, this is a big swing. Great early. - JM"]
	},
	{
		name: "Black Hole",
		character: "Gravity Girl",
		type: "Feat",
		utilityValues: ["../../public/images/gg-blackhole.png"],
		text: "Each player discards their hand, then draws that many cards.",
		flavor: [""],
		illustrations: [""],
		rating: [""],
		tags: ["versatile", "player damage", "feat"],
		comments: ["Keeps the pressure up. Very strong mid-game. - JM"]
	},
	{
		name: "Dunk",
		character: "Gravity Girl",
		type: "Feat",
		utilityValues: [""],
		text: "Throw. Deal 6 damage to target Utility.",
		flavor: [""],
		illustrations: ["../../public/images/gg-dunk.png"],
		rating: [""],
		tags: ["versatile", "utility damage", "feat"],
		comments: ["Get out of jail free card. Use wisely. - JM"]
	},
	{
		name: "Fit Of Anger",
		character: "Gravity Girl",
		type: "Feat",
		utilityValues: [""],
		text: "Play an Action card from your hand for free, then play an Action card from your hand for free.",
		flavor: [""],
		illustrations: ["../../public/images/gg-fitofanger.png"],
		rating: [""],
		tags: ["combo", "build-around", "feat"],
		comments: ["Combo enabler. Doesn't work in every build. - JM"]
	},
	{
		name: "Gravity Well",
		character: "Gravity Girl",
		type: "Feat",
		utilityValues: [""],
		text: "Destroy each of your Utilities. Deal 3 damage to each opponent.",
		flavor: [""],
		illustrations: ["../../public/images/gg-gravitywell.png"],
		rating: [""],
		tags: ["aggressive", "build-around", "feat"],
		comments: ["Build around. This + Shrapnel Storm = big game. - JM"]
	},
	{
		name: "Reverse Time",
		character: "Gravity Girl",
		type: "Feat",
		utilityValues: [""],
		text: "Refresh the armor value on each of your Utilities. Draw 2 cards.",
		flavor: [""],
		illustrations: ["../../public/images/gg-reversetime.png"],
		rating: [""],
		tags: ["defensive", "card draw", "armor", "build-around", "feat"],
		comments: ["Buys a surprising amount of time. Defensive but useful in any build. - JM"]
	},
	{
		name: "Anti-Virus",
		character: "Robonobo",
		type: "Action",
		utilityValues: [""],
		text: "Double target Utility's current armor.",
		flavor: ["The internet gave Robo a headache."],
		illustrations: ["../../public/images/rb-antivirus.png"],
		rating: [""],
		tags: ["combo", "defensive", "armor"],
		comments: ["Can be a huge swing. Big combo with Monkey See, Monkey Do - JM"]
	},
	{
		name: "Back Plating",
		character: "Robonobo",
		type: "Utility",
		utilityValues: ["3","0","6"],
		text: "",
		flavor: ["Robo want to look like bodybuilders on the internet."],
		illustrations: ["../../public/images/rb-backplating.png"],
		rating: [""],
		tags: ["defensive", "armor"],
		comments: ["More useful as distraction. Opponents will go after big Armor aggressively. - JM"]
	},
	{
		name: "Bomb Vent",
		character: "Robonobo",
		type: "Utility",
		utilityValues: ["1","4","4"],
		text: "",
		flavor: ["Robo think new bomb vent good, but hard to clean."],
		illustrations: ["../../public/images/rb-bombvent.png"],
		rating: [""],
		tags: ["aggressive", "armor"],
		comments: ["Giant target. This almost never survives a turn. - JM"]
	},	
	{
		name: "Charge Cable",
		character: "Robonobo",
		type: "Utility",
		utilityValues: ["3","3","0"],
		text: "When you play this, you may Evolve.",
		flavor: ["Why Robo...ZZZZZZ...at school...ZZZZZZ...no pants..."],
		illustrations: ["../../public/images/rb-chargecable.png"],
		rating: [""],
		tags: ["aggressive", "evolve"],
		comments: ["Stats and immediate Evolve trigger makes this a great role-filler. - JM"]
	},
	{
		name: "Darwin Matrix",
		character: "Robonobo",
		type: "Utility",
		utilityValues: ["3","0","0"],
		text: "At the end of your turn, you may Evolve.",
		flavor: ["Knox, who is Scopes? Monkey trial sounds fun!"],
		illustrations: ["../../public/images/rb-darwinmatrix.png"],
		rating: [""],
		tags: ["combo", "build-around", "evolve"],
		comments: ["Not gonna win a game with this, but good for synergy decks. - JM"]
	},
	{
		name: "Empty Cache",
		character: "Robonobo",
		type: "Action",
		utilityValues: [""],
		text: "Evolve. Draw 2 cards.",
		flavor: ["Knox, you got any more laser snacks?"],
		illustrations: ["../../public/images/rb-emptycache.png"],
		rating: [""],
		tags: ["versatile", "card draw", "evolve"],
		comments: ["Almost always good but never gradiose. Great 30th card. - JM"]
	},
	{
		name: "Gorilla Press",
		character: "Robonobo",
		type: "Action",
		utilityValues: [""],
		text: "Target Utility gets +3 fight this turn.",
		flavor: ["Robo say Robomania is running wild."],
		illustrations: ["../../public/images/rb-gorillapress.png"],
		rating: [""],
		tags: ["aggressive", "fight"],
		comments: ["Strong damage source for Robo. Stronger than it looks because of Robo's limited Utility damage. - JM"]
	},
	{
		name: "Grooming",
		character: "Robonobo",
		type: "Action",
		utilityValues: [""],
		text: "Target Utility gets +2 fight this turn. If you've activated a Feat this turn, that Utility also gets +2 armor.",
		flavor: ["Robo say it not a crime to look good."],
		illustrations: ["../../public/images/rb-grooming.png"],
		rating: [""],
		tags: ["versatile", "fight", "armor"],
		comments: ["Completely middle of the road, but playable in aggro and armor combo builds. - JM"]
	},
	{
		name: "Guidance Systems",
		character: "Robonobo",
		type: "Utility",
		utilityValues: ["2","2","3"],
		text: "Whenever this deals damage to an opponent, you may Evolve.",
		flavor: ["Robo's guidance system aims, but it find candy too."],
		illustrations: ["../../public/images/rb-guidancesystems.png"],
		rating: [""],
		tags: ["versatile", "armor", "evolve"],
		comments: ["Very popular in playtesting, but I don't see it. Completely fine and fragile. - JM"]
	},
	{
		name: "Logic Chain",
		character: "Robonobo",
		type: "Action",
		utilityValues: [""],
		text: "Evolve. 2 damage to target opponent.",
		flavor: ["if (mad) then {punch} else {prank}"],
		illustrations: ["../../public/images/rb-logicchain.png"],
		rating: [""],
		tags: ["aggressive", "player damage", "evolve"],
		comments: ["If you need an Evolve trigger, this is probably the worst. Works better in aggressive decks. - JM"]
	},
	{
		name: "Laser Cannon",
		character: "Robonobo",
		type: "Utility",
		utilityValues: ["2","2","3"],
		text: "Whenever you Evolve, 3 damage to target Utility owned by an opponent.",
		flavor: ["Robo practice this part online. 360 no scope."],
		illustration: ["../../public/images/rb-lasercannon.png"],
		rating: [""],
		tags: ["aggressive", "utility damage", "combo", "evolve"],
		comments: ["Better in the evolve deck, but a rock star in every game. Combos with Monkey Wrench. - JM"]
	}
	{
		name: "Microchimp Processor",
		character: "Robonobo",
		type: "Utility",
		utilityValues: ["1","4","0"],
		text: "Whenever you play your second Action in a turn, you may Evolve.",
		flavor: ["Robo now smart as 1000 apes. That's a lot of apes."],
		illustrations: ["../../public/images/rb-microchimpprocessor.png"],
		rating: [""],
		tags: ["combo", "evolve"],
		comments: ["Will basically stay on the board the entire game. Great early play and hard to get rid of. - JM"]
	},
	{
		name: "Monkey See Monkey Do",
		character: "Robonobo",
		type: "Action",
		utilityValues: [""],
		text: "This is a copy of the last Action card you played this turn.",
		flavor: ["Robo want to drive the tank too!"],
		illustrations: ["../../public/images/rb-monkeyseemonkeydo.png"],
		rating: [""],
		tags: ["combo", "build-around"],
		comments: ["Anti-Virus. Gorilla Press. Empty Cache. Monkey's Paw. Brutal card. Bomb. - JM"]
	},
	{
		name: "Monkey's Paw",
		character: "Robonobo",
		type: "Action",
		utilityValues: [""],
		text: "Deal 2 damage to target Utility. If all of your Feats are face-down, destroy it instead.",
		flavor: ["Robo think you have bad luck."],
		illustrations: ["../../public/images/rb-monkeyspaw.png"],
		rating: [""],
		tags: ["versatile", "utility damage"],
		comments: ["Robo's limited Utility damage makes this a strong sideboard card. - JM"]
	},
	{
		name: "Overclocked Fists",
		character: "Robonobo",
		type: "Action",
		utilityValues: [""],
		text: "Deal two damage to target Opponent. If all of your Feats are face-down, 4 damage instead.",
		flavor: ["Knox! Robo can't stop punching!"],
		illustrations: ["../../public/images/rb-overclockedfists.png"],
		rating: [""],
		tags: ["aggressive", "player damage"],
		comments: ["Doesn't work well in the Evolve deck, but aggressive Rocket Punch decks can use this. - JM"]
	},
	{
		name: "Robo Has Idea!",
		character: "Robonobo",
		type: "Utility",
		utilityValues: ["3","0","0"],
		text: "Whenever you Evolve, you may destroy this. If you do, deal 3 damage to target Opponent.",
		flavor: ["Uh...Robo forgot what it was."],
		illustrations: ["../../public/images/rb-robohasidea.png"],
		rating: [""],
		tags: ["aggressive", "player damage", "combo"],
		comments: ["Oddly enough, much worse in the Evolve deck. Aggro builds love this easy damage though. - JM"]
	},
	{
		name: "Skull Plating",
		character: "Robonobo",
		type: "Utility",
		utilityValues: ["4","0","5"],
		text: "",
		flavor: ["Robo's thick skull is now much thicker. Robo smart."],
		illustrations: ["../../public/images/rb-skullplating.png"],
		rating: [""],
		tags: ["defensive", "armor"],
		comments: ["Robo's best defensive option - solid as a rock. Always works. Loves Anti-Virus. - JM"]
	},
	{
		name: "Steel Gauntlet",
		character: "Robonobo",
		type: "Utility",
		utilityValues: ["3","1","3"],
		text: "",
		flavor: ["Robo protect hands. Robo need hands for video games."],
		illustrations: ["../../public/images/rb-steelgauntlet.png"],
		rating: [""],
		tags: ["defensive", "armor"],
		comments: ["Very playable as a 30th card. Doesn't win a game, but usually soaks damage and helps with Utility removal. - JM"]
	},
	{
		name: "Updating...",
		character: "Robonobo",
		type: "Action",
		utilityValues: [""],
		text: "Evolve twice.",
		flavor: ["Robo can't do chores today. Updates."],
		illustrations: ["../../public/images/rb-updating.png"],
		rating: [""],
		tags: ["combo", "build-around", "evolve"],
		comments: ["Don't play this in offensive decks. It kind of does nothing. Laser Cannons likes it.- JM"]
	},
	{
		name: "Wrist Weapon",
		character: "Robonobo",
		type: "Utility",
		utilityValues: ["4","0","0"],
		text: "Whenever you activate a Feat, this gets +2 fight this turn.",
		flavor: ["Robo's new arm has spring-loaded action."],
		illustrations: ["../../public/images/rb-wristweapon.png"],
		rating: [""],
		tags: ["versatile", "combo", "evolve"],
		comments: ["Not the most aggressive card, but reliable and tough to kill. - JM"]
	},
	{
		name: "Ape Omega",
		character: "Robonobo",
		type: "Crossover",
		utilityValues: ["3","2","0"],
		text: "Whenever you play another Utility, deal 2 damage to each player.",
		flavor: ["Insurance Companies Hate This One Weird Chimp"],
		illustrations: ["../../public/images/cross-apeomega.png"],
		rating: [""],
		tags: ["aggressive", "combo", "player damage", "crossover"],
		comments: ["Racks up the damage. Punishes players without Armor. - JM"]
	},
	{
		name: "U.S. Ape",
		character: "Robonobo",
		type: "Crossover",
		utilityValues: ["3","2","0"],
		text: "At the beginning of your turn, you may discard a card. If you do, your other Utilities get +1 fight this turn.",
		flavor: ["This Patriot's Ape Army Is Coming To Tread On You"],
		illustrations: ["../../public/images/cross-usape.png"],
		rating: [""],
		tags: ["aggressive", "discard", "crossover"],
		comments: ["If you can keep a full hand, this is great for a pressure game. Semper Fi! - JM"]
	},
	{
		name: "Fling",
		character: "Robonobo",
		type: "Feat",
		utilityValues: [""],
		text: "Target Utility gets +1 fight this turn.",
		flavor: [""],
		illustrations: ["../../public/images/rb-fling.png"],
		rating: [""],
		tags: ["aggressive", "versatile", "feat"],
		comments: ["Better than you think. Works in almost every deck, but keeps the aggressive deck going long into the mid-game."]
	},
	{
		name: "Funny Prank",
		character: "Robonobo",
		type: "Feat",
		utilityValues: [""],
		text: "Each player discards a card.",
		flavor: [""],
		illustrations: ["../../public/images/rb-funnyprank.png"],
		rating: [""],
		tags: ["defensive", "discard", "disruption", "feat"],
		comments: ["This can honestly be very brutal in an Evolve deck. It doesn't take long to start whittling down hands. - JM"]
	},
	{
		name: "Monkey Wrench",
		character: "Robonobo",
		type: "Feat",
		utilityValues: [""],
		text: "Evolve, then Evolve again.",
		flavor: [""],
		illustrations: ["../../public/images/rb-monkeywrench.png"],
		rating: [""],
		tags: ["combo", "build-around", "feat"],
		comments: ["Doesn't work in every deck, but combos well and keeps the aggressive deck in new feats. - JM"]
	},
	{
		name: "Rocket Punch",
		character: "Robonobo",
		type: "Feat",
		utilityValues: [""],
		text: "Deal 2 damage to each opponent.",
		flavor: [""],
		illustrations: ["../../public/images/rb-rocketpunch.png"],
		rating: [""],
		tags: ["aggressive", "player damage", "feat"],
		comments: ["Use it every turn if you can. It's very good, but vulnerable to armor-heavy builds. - JM"]
	},	
	{
		name: "Jailbreak",
		character: "Robonobo",
		type: "Feat",
		utilityValues: [""],
		text: "Each player draws a card.",
		flavor: [""],
		illustrations: ["../../public/images/rb-jailbreak.png"],
		rating: [""],
		tags: ["versatile", "card draw", "feat"],
		comments: ["Keeps your hand full if you don't want to make space in your deck for card draw. Combos like it too. - JM"]
	},
	{
		name: "Buckshot",
		character: "Deadeye",
		type: "Action",
		utilityValues: [""],
		text: "To play this, you must first discard a card. 1 damage to target opponent and each of their Utilities.",
		flavor: ["Don't bother ducking, idiots."],
		illustrations: ["../../public/images/de-buckshot.png"],
		rating: [""],
		tags: ["aggressive", "player damage", "utility damage", "discard"],
		comments: ["Powerful card in a deck with consistent aim. Low floor. - JM"]
	},
	{
		name: "Calling Shots",
		character: "Deadeye",
		type: "Action",
		utilityValues: [""],
		text: "Each opponent discards a card at random. Draw 2 cards.",
		flavor: ["Which one? Blah. Doesn't matter."],
		illustrations: ["../../public/images/de-callingshots.png"],
		rating: [""],
		tags: ["disruption", "card draw", "combo", "discard"],
		comments: ["Better in a discard-based deck, but Deadeye needs some draw. It's fine. - JM"]
	},
	{
		name: "Clip Ankle",
		character: "Deadeye",
		type: "Action",
		utilityValues: [""],
		text: "Deal 2 damage to target player. That player discards a card.",
		flavor: ["Ouch! Must be the shoes."],
		illustrations: ["../../public/images/de-clipankle.png"],
		rating: [""],
		tags: ["disruption", "discard", "player damage"],
		comments: ["Usually gets a card and some armor. Great filler card. - JM"]
	},
	{
		name: "Decent Cover",
		character: "Deadeye",
		type: "Utility",
		utilityValues: ["4","0","4"],
		text: "",
		flavor: ["Well...can't shoot anybody if I'm dead."],
		illustrations: ["../../public/images/de-decentcover.png"],
		rating: [""],
		tags: ["defensive", "armor"],
		comments: ["Deadeye doesn't get a lot of defensive options and this is great with Duck Down. - JM"]
	},
	{
		name: "Drawing A Bead",
		character: "Deadeye",
		type: "Action",
		utilityValues: [""],
		text: "Discard up to three cards. Aim +1 for each card discarded.",
		flavor: ["Wait for it...Wait for it..."],
		illustrations: ["../../public/images/de-drawingabead.png"],
		rating: [""],
		tags: ["combo", "discard", "aim"],
		comments: ["Great combo piece in an aim deck. 3 aim out of one card is a bargain. - JM"]
	},
	{
		name: "Duck Down",
		character: "Deadeye",
		type: "Action",
		utilityValues: [""],
		text: "Search your deck for a Utility with 3 or more Armor and draw it. Shuffle your deck after.",
		flavor: ["Come and get me!"],
		illustrations: ["../../public/images/de-duckdown.png"],
		rating: [""],
		tags: ["defensive", "armor"],
		comments: ["Grabs crossovers too, but plays well with Decent Cover. - JM"]
	},
	{
		name: "Empty The Clip",
		character: "Deadeye",
		type: "Action",
		utilityValues: [""],
		text: "To play this, you must first discard two cards. 4 damage to target opponent.",
		flavor: ["I hate wasting my bullets on you."],
		illustrations: ["../../public/images/de-emptythechamber.png"],
		rating: [""],
		tags: ["aggressive", "player damage", "discard"],
		comments: ["Hits hard and eats armor. - JM"]
	},
	{
		name: "Explosive Rounds",
		character: "Deadeye",
		type: "Action",
		utilityValues: [""],
		text: "Aim +2. 1 damage to any target.",
		flavor: ["Like a hot knife through butter."],
		illustrations: ["../../public/images/de-explosiverounds.png"],
		rating: [""],
		tags: ["versatile", "combo", "player damage", "utility damage", "aim"],
		comments: ["This card does everything. Bomb. - JM"]
	},
	{
		name: "Ghost Magnum",
		character: "Deadeye",
		type: "Utility",
		utilityValues: ["1","3","0"],
		text: "At the beginning of your turn, Aim +1.",
		flavor: ["Perfectly untraceable."],
		illustrations: ["../../public/images/de-ghostmagnum.png"],
		rating: [""],
		tags: ["aggressive", "aim"],
		comments: ["If you're looking for damage, this delivers. Don't expect it to stick around. - JM"]
	},
	{
		name: "Hail Of Bullets",
		character: "Deadeye",
		type: "Action",
		utilityValues: [""],
		text: "Target Utility gains Fight equal to your Aim Score until end of turn.",
		flavor: ["Nowhere to run. Nowhere to hide."],
		illustrations: ["../../public/images/de-pinemdown.png"],
		rating: [""],
		tags: ["versatile", "combo", "fight", "aim"],
		comments: ["If you get 2 or more out of this, it can close a game or break a utility. Great card. - JM"]
	},
	{
		name: "Hollow Point Bandolier",
		character: "Deadeye",
		type: "Utility",
		utilityValues: ["3","2","0"],
		text: "At the beginning of your turn, Aim +1.",
		flavor: ["It's like a big necklace that makes me money."],
		illustrations: ["../../public/images/de-hollowpointbandolier.png"],
		rating: [""],
		tags: ["versatile", "aim"],
		comments: ["The HP makes this a consistent source of damage. Might draw attention. - JM"]
	},
	{
		name: "Laser Sights",
		character: "Deadeye",
		type: "Utility",
		utilityValues: ["4","0","0"],
		text: "At the beginning of your turn, Aim +1.",
		flavor: [""],
		illustrations: ["../../public/images/de-lasersights.png"],
		rating: [""],
		tags: ["combo", "aim"],
		comments: ["Use at your own risk. Great source of Aim, but does nothing else. - JM"]
	},
	{
		name: "Muzzle Flare",
		character: "Deadeye",
		type: "Action",
		utilityValues: [""],
		text: "Target opponent discards a card at random. If that card is an Action, 2 damage to each opponent.",
		flavor: ["Bad move. You got too close."],
		illustrations: ["../../public/images/de-youtryingtorun.png"],
		rating: [""],
		tags: ["disruption", "discard", "player damage"],
		comments: ["Good for the discard toolkit. Random discard is very brutal with 2-3 cards in hand. - JM"]
	},
	{
		name: "Opening Salvo",
		character: "Deadeye",
		type: "Action",
		utilityValues: [""],
		text: "Aim +2. 1 damage to any target.",
		flavor: ["I hate every single one of you."],
		illustrations: ["../../public/images/de-openingsalvo.png"],
		rating: [""],
		tags: ["versatile", "player damage", "utility damage", "aim", "combo"],
		comments: ["Does everything. Play at least one in every deck. - JM"]
	},
	{
		name: "Reload",
		character: "Deadeye",
		type: "Action",
		utilityValues: [""],
		text: "Draw three cards.",
		flavor: ["C'mon...C'mon...one more second..."],
		illustrations: ["../../public/images/de-reload.png"],
		rating: [""],
		tags: ["defensive", "card draw"],
		comments: ["Deadeye struggles for card draw and this is pretty bog standard. - JM"]
	},
	{
		name: "Semi-Auto Spread",
		character: "Deadeye",
		type: "Action",
		utilityValues: [""],
		text: "Discard any number of cards. 2 damage to that many different targets.",
		flavor: ["I'm about to get the high score!"],
		illustrations: ["../../public/images/de-semiauto.png"],
		rating: [""],
		tags: ["versatile", "player damage", "utility damage"],
		comments: ["It isn't wrong to do this for one or two targets, but you need Aim to make it sing. - JM"]
	},

	{
		name: "Splash Damage",
		character: "Deadeye",
		type: "Utility",
		utilityValues: ["5","0","0"],
		text: "At the end of your turn, if your Aim Score is 3 or higher, each player discards two cards.",
		flavor: ["Keep your head down. Or not. I don't care."],
		illustrations: ["../../public/images/de-splashdamage.png"],
		rating: [""],
		tags: ["disruption", "discard", "combo"],
		comments: ["You won't need to use this too many times to empty everyone's hand. Good in the Aim deck. - JM"]
	},
	{
		name: "Spoils Of War",
		character: "Deadeye",
		type: "Action",
		utilityValues: ["2","0","0"],
		text: "Whenever a player discards one or more cards from their hand, draw exactly that many cards.",
		flavor: ["You're getting mad. I'm getting rich."],
		illustrations: ["../../public/images/de-spoilsofwar.png"],
		rating: [""],
		tags: ["combo", "disruption", "discard"],
		comments: ["Don't let this stay on the board too long or you'll pay for it. - JM"]
	},
	{
		name: "Spotting Targets",
		character: "Deadeye",
		type: "Action",
		utilityValues: [""],
		text: "Aim +2. Draw a card.",
		flavor: ["I can't decide. They all look stupid."],
		illustrations: ["../../public/images/de-targetspotted.png"],
		rating: [""],
		tags: ["combo", "defensive", "card draw", "aim"],
		comments: ["Excellent in the aim deck, but not great alone. - JM"]
	},
	{
		name: "Staredown",
		character: "Deadeye",
		type: "Action",
		utilityValues: [""],
		text: "To play this, you must first discard a card. Each opponent discards two cards.",
		flavor: ["Go ahead. Try to shoot first."],
		illustrations: ["../../public/images/de-smokeemout.png"],
		rating: [""],
		tags: ["disruption", "discard"],
		comments: ["Excellent in the discard deck, but not unbeatable. Card draw can stuff this deck quickly. - JM"]
	},
	{
		name: "Suppressive Fire",
		character: "Deadeye",
		type: "Utility",
		utilityValues: ["4","0","0"],
		text: "At the beginning of your turn, you may discard two cards. If you do, destroy target Utility.",
		flavor: [""],
		illustrations: ["../../public/images/de-suppressivefire.png"],
		rating: [""],
		tags: ["aggressive", "utility damage", "discard"],
		comments: ["You can't do this every turn, but once is good enough. - JM"]
	},
	{
		name: "Trick Shot",
		character: "Deadeye",
		type: "Action",
		utilityValues: [""],
		text: "Aim +1. Deal 2 damage to target Utility.",
		flavor: ["Check out the walking bullseye."],
		illustrations: ["../../public/images/de-cleansnipe.png"],
		rating: [""],
		tags: ["aggressive", "utility damage", "aim"],
		comments: ["Very good against a full board. Not worth playing just for the aim. - JM"]
	},
	{
		name: "Riot Grrrl",
		character: "Deadeye",
		type: "Crossover",
		utilityValues: ["1","3","0"],
		text: "At the beginning of your turn, you may discard two cards. If you do, your Utilities are a copy of Riot Grrrl this turn.",
		flavor: ["One-Woman Rave With Expensive Taste"],
		illustrations: ["../../public/images/cross-riotgrrrl.png"],
		rating: [""],
		tags: ["crossover", "discard", "aggressive"],
		comments: ["Guaranteed nine damage with a full board. Great if you can keep it safe. - JM"]
	},
	{
		name: "Thwip!",
		character: "Deadeye",
		type: "Crossover",
		utilityValues: ["3","2","0"]		],
		text: "When you play this, prevent all damage that would be done to you and your Utilities until your next turn.",
		flavor: ["Superhero Archer Tailing Her Dirtbag Sister."],
		illustrations: ["../../public/images/cross-thwip.png"],
		rating: [""],
		tags: ["crossover", "defensive"],
		comments: ["Great way to keep your combo deck alive for one turn. - JM"]
	},
		{
		name: "Bullseye!",
		character: "Deadeye",
		type: "Feat",
		utilityValues: [""],
		text: "Deal damage to each opponent equal to the number of cards in their hand.",
		flavor: [""],
		illustrations: ["../../public/images/de-bullseye.png"],
		rating: [""],
		tags: ["aggressive", "player damage"],
		comments: ["Don't play this in the discard deck. - JM"]
	},
	{
		name: "Hands Up!",
		character: "Deadeye",
		type: "Feat",
		utilityValues: [""],
		text: "Each player discards two cards.",
		flavor: [""],
		illustrations: ["../../public/images/de-handsup.png"],
		rating: [""],
		tags: ["aggressive", "disruption"],
		comments: ["Nauseating turn one play. - JM"]
	},
	{
		name: "Kneecap",
		character: "Deadeye",
		type: "Feat",
		utilityValues: [""],
		text: "Reveal cards from the top of your deck until you find an Action. Play that card for free and discard the rest.",
		flavor: [""],
		illustrations: ["../../public/images/de-handsup.png"],
		rating: [""],
		tags: ["versatile", "combo"],
		comments: ["If you get a free action, you can spend both of your other plays building aim. - JM"]
	},
	{
		name: "New Clip",
		character: "Deadeye",
		type: "Feat",
		utilityValues: [""],
		text: "Draw three cards.",
		flavor: [""],
		illustrations: ["../../public/images/de-handsup.png"],
		rating: [""],
		tags: ["defensive", "card draw"],
		comments: ["Deadeye needs to keep her hands full to use her more explosive aim cards. - JM"]
	},
	{
		name: "Sureshot",
		character: "Deadeye",
		type: "Feat",
		utilityValues: [""],
		text: "Aim +1, 3 damage to target Utility.",
		flavor: [""],
		illustrations: ["../../public/images/de-handsup.png"],
		rating: [""],
		tags: ["agggresive", "utility damage", "aim"],
		comments: ["You'll need this to get those pesky combo decks out of the way. - JM"]
	},
	{
		name: "Aggressive Bodyguard",
		character: "Knox",
		type: "Utility",
		utilityValues: ["4","4","0"],
		text: "Minion. To play this, you must first discard two cards.",
		flavor: ["Down boy! Oooh, this one has some spice. I like it!"],
		illustrations: ["../../public/images/kx-aggressivebodyguard.png"],
		rating: [""],
		tags: ["aggressive", "discard", "minion"],
		comments: ["Keeping this alive for a turn or two can make up for the high cost. - JM"]
	},
	{
		name: "Angry Lunge",
		character: "Knox",
		type: "Action",
		utilityValues: [""],
		text: "Deal 4 damage to any target and yourself.",
		flavor: ["Submit to you? I'd rather die!"],
		illustrations: ["../../public/images/kx-angrylunge.png"],
		rating: [""],
		tags: ["aggressive", "player damage", "utility damage"],
		comments: ["Can always scrub a minion to avoid the penalty. - JM"]
	},
	{
		name: "Bank Robber",
		character: "Knox",
		type: "Utility",
		utilityValues: ["2","2","0"],
		text: "Minion. When this is destroyed, skip your discard phase this turn.",
		flavor: ["I'd do it myself, but who has the time"],
		illustrations: ["../../public/images/kx-bankrobber.png"],
		rating: [""],
		tags: ["combo", "card draw", "minion"],
		comments: ["Only works if he dies on your turn. Minion him to save some damage.- JM"]
	},
	{
		name: "Bomb Threat",
		character: "Knox",
		type: "Utility",
		utilityValues: ["1","2","0"],
		text: "If you have seven or more cards in your hand at the end of your turn, you may destroy this and 5 damage to target opponent.",
		flavor: ["Yes, there is a bomb. No, I don't know how it works."],
		illustrations: ["../../public/images/kx-bombthreat.png"],
		rating: [""],
		tags: ["combo", "player damage"],
		comments: ["Doesn't hurt to throw this out there so your opponent will waste some removal. - JM"]
	},
	{
		name: "Cannon Fodder",
		character: "Knox",
		type: "Utility",
		utilityValues: ["1","4","0"],
		text: "Minion.",
		flavor: ["What's your name again? Tom? Go get 'em, Tom."],
		illustrations: ["../../public/images/kx-cannonfodder.png"],
		rating: [""],
		tags: ["versatile", "minion"],
		comments: ["Will hang around to soak some damage for as long as you want him. - JM"]
	},
	{
		name: "Cut-Rate Mercenary",
		character: "Knox",
		type: "Utility",
		utilityValues: ["2","2","0"],
		text: "Minion. When you play this, draw a card.",
		flavor: [""],
		illustrations: ["../../public/images/kx-cutratemercenary.png"],
		rating: ["Which one of you buffoons spilled ink on the money?"],
		tags: ["versatile", "card draw", "minion"],
		comments: ["I always play this - it replaces itself and is good early. - JM"]
	},
	{
		name: "Cheap Shot",
		character: "Knox",
		type: "Action",
		utilityValues: [""],
		text: "Deal 2 damage to each opponent. If you have six or more cards in your hand, you may play this card for free.",
		flavor: [""],
		illustrations: ["../../public/images/kx-cheapshot.png"],
		rating: [""],
		tags: ["combo", "aggressive", "card draw", "player damage"],
		comments: ["Not worth it without the bonus, but the card draw deck is real and dangerous. - JM"]
	},
	{
		name: "Collateral Damage",
		character: "Knox",
		type: "Action",
		utilityValues: [""],
		text: "Deal 4 damage to each player.",
		flavor: ["This sort of thing runs in the family."],
		illustrations: ["../../public/images/kx-collateraldamage.png"],
		rating: [""],
		tags: ["aggressive", "player damage"],
		comments: ["You can always minion this away. - JM"]
	},
	{
		name: "Donaldson, The Butler",
		character: "Knox",
		type: "Utility",
		utilityValues: ["4","0","2"],
		text: "Minion. You have no maximum hand size.",
		flavor: ["DONALDSON! Time to feed the feral dogs! Where is he?"],
		illustrations: ["../../public/images/kx-donaldsonthebutler.png"],
		rating: [""],
		tags: ["defensive", "armor", "card draw", "minion"],
		comments: ["The ultimate minion. You can stack armor on this guy all day long. - JM"]
	},
	{
		name: "Endless Ambition",
		character: "Knox",
		type: "Utility",
		utilityValues: ["3","0","0"],
		text: "Whenever you draw a card, 1 damage to each opponent.",
		flavor: ["I will not stop until the world fears the name of Knox!"],
		illustrations: ["../../public/images/kx-endlessambition.png"],
		rating: [""],
		tags: ["combo", "defensive", "card draw"],
		comments: ["Good in the card draw deck, but aggressive decks might want something with fight. - JM"]
	},
	{
		name: "Expensive Goon",
		character: "Knox",
		type: "Utility",
		utilityValues: ["4","4","0"],
		text: "Minion. At the end of your turn, discard a card or destroy this.",
		flavor: ["The check is in the mail. Please don't hurt me."],
		illustrations: ["../../public/images/kx-expensivegoon.png"],
		rating: [""],
		tags: ["aggressive", "minion", "discard"],
		comments: ["Worth the cost. Goon + Bodyguard is very hard to come back from. - JM"]
	},
	{
		name: "Extorting The Board",
		character: "Knox",
		type: "Utility",
		utilityValues: ["3","0","3"],
		text: "At the end of your turn, draw a card.",
		flavor: ["After what happened to my last board, I expect fealty."],
		illustrations: ["../../public/images/kx-extorttheboard.png"],
		rating: [""],
		tags: ["defensive", "combo", "card draw", "armor"],
		comments: ["It won't win you the game, but it buys you a turn or two. Big target. - JM"]
	},
	{
		name: "Father's Inheritance",
		character: "Knox",
		type: "Utility",
		utilityValues: ["5","0","2"],
		text: "At the beginning of your turn, you may destroy this. If you do, draw three cards.",
		flavor: ["His empire. His pistol. His failures. All mine to keep."],
		illustrations: ["../../public/images/kx-fathersvault.png"],
		rating: [""],
		tags: ["defensive", "card draw", "armor"],
		comments: ["Slots perfectly into the slower card draw combo deck. I've been impressed by this. - JM"]
	},
	{
		name: "Flood The Streets",
		character: "Knox",
		type: "Utility",
		utilityValues: ["4","0","0"],
		text: "Whenever you play a Utility with Minion, draw a card and skip your discard phase this turn.",
		flavor: ["Shouldn't you be doing crime, Ted? Get out of my pool."],
		illustrations: ["../../public/images/kx-floodthestreets.png"],
		rating: [""],
		tags: ["combo", "card draw", "minion"],
		comments: ["The aggressive deck runs a lot of minions and this will help you if you run out of gas. - JM"]
	},
	{
		name: "Get Them You Idiots!",
		character: "Knox",
		type: "Action",
		utilityValues: [""],
		text: "Target Utility gets +2 Fight this turn. Draw 2 cards.",
		flavor: ["Why do we only hire awful henchmen?"],
		illustrations: ["../../public/images/kx-getthemyouidiots.png"],
		rating: [""],
		tags: ["aggressive", "card draw"],
		comments: ["Pretty flexible, to be honest. Knox likes to run a lot of minions and this keeps the pressure up. - JM"]
	},
	{
		name: "Harass & Demean",
		character: "Knox",
		type: "Action",
		utilityValues: [""],
		text: "To play this, you must first discard a Utility card. Destroy target Utility.",
		flavor: ["Eye for an eye? Only if you are weak."],
		illustrations: ["../../public/images/kx-harassanddemean.png"],
		rating: [""],
		tags: ["disruption", "discard", "utility damage"],
		comments: ["Unconditional removal is very powerful. Don't overlook this. - JM"]
	},
	{
		name: "Incoherent Ranting",
		character: "Knox",
		type: "Utility",
		utilityValues: ["3","0","2"],
		text: "At the end of your turn, 2 damage to each player.",
		flavor: ["...are too dumb to reason with my brilliance! And..."],
		illustrations: ["../../public/images/kx-incessantranting.png"],
		rating: [""],
		tags: ["aggressive", "combo", "player damage"],
		comments: ["Knox needs the game to end quickly and this definitely fits the bill. - JM"]
	},
	{
		name: "Moronic Gangster",
		character: "Knox",
		type: "Utility",
		utilityValues: ["3","3","0"],
		text: "Minion.",
		flavor: ["Don't you think that kevlar would just slow you down?"],
		illustrations: ["../../public/images/kx-incessantranting.png"],
		rating: [""],
		tags: ["versatile", "minion"],
		comments: ["Solid stats. Don't do much, but does it well. - JM"]
	},
	{
		name: "Shatter To Bits",
		character: "Knox",
		type: "Action",
		utilityValues: [""],
		text: "Deal damage to target Utility equal to its current Armor Value. Draw a card.",
		flavor: ["Broken! All of your toys are broken!"],
		illustrations: ["../../public/images/kx-shattertobits.png"],
		rating: [""],
		tags: ["disruption", "card draw", "utility damage"],
		comments: ["This is a great sideboard card between matches. Excellent against pillowfort decks. - JM"]
	},
	{
		name: "Sinister Machinations",
		character: "Knox",
		type: "Action",
		utilityValues: [""],
		text: "Reveal any number of Utility cards from your hand. Target Utility gets +1 Armor for each card revealed.",
		flavor: ["We have a plan! Stick to the plan!"],
		illustrations: ["../../public/images/kx-sinistermachinations.png"],
		rating: [""],
		tags: ["defensive", "card draw", "combo", "armor"],
		comments: ["The card draw deck needs a bit of time and Donaldson is happy to take your orders." - JM]
	},
	{
		name: "Unfurling Schemes",
		character: "Knox",
		type: "Action",
		utilityValues: [""],
		text: "Draw the top 2 cards of your discard pile.",
		flavor: ["Draw the top 2 cards of your discard pile."],
		illustrations: ["../../public/images/kx-unfurlingschemes.png"],
		rating: [""],
		tags: ["versatile", "card draw", "combo"],
		comments: ["This is so much better than drawing two off the top of the deck. - JM"]
	},
	{
		name: "Violent Strike",
		character: "Knox",
		type: "Action",
		utilityValues: [""],
		text: "3 damage to target Utility. If you have 6 or more cards in your hand, you may play this card for free.",
		flavor: ["Deadeye, can you take care of this?"],
		illustrations: ["../../public/images/kx-viciousstrike.png"],
		rating: [""],
		tags: ["combo", "utility damage", "card draw"],
		comments: ["This is playable without the bonus but excellent with it. - JM"]
	},
	{
		name: "Dark Belle",
		character: "Knox",
		type: "Crossover",
		utilityValues: ["2","3","0"],
		text: "Whenever this deals damage to an opponent, you may look at that player's hand and discard a card form it.",
		flavor: ["A Failure Of Science Fueled By Hatred"],
		illustrations: ["../../public/images/cross-darkbelle.png"],
		rating: [""],
		tags: ["aggressive", "disruption", "discard"],
		comments: ["Probably the strongest turn one play in the game. - JM"]
	},
	{
		name: "Massacre",
		character: "Knox",
		type: "Crossover",
		utilityValues: ["2","4","0"],
		text: "When you play this, destroy all Utilities whose current Armor value is four or higher.",
		flavor: ["Eight Arms To Choke You"],
		illustrations: ["../../public/images/cross-massacre.png"],
		rating: [""],
		tags: ["defensive", "armor", "disruption"],
		comments: ["Doesn't fit in every deck, but helps to break open defensive decks or setup utility destruction combos. - JM"]
	},		
	{
		name: "Cruel Plot",
		character: "Knox",
		type: "Feat",
		utilityValues: [""],
		text: "Discard your hand. 1 damage to each opponent for each card discarded this way.",
		flavor: [""],
		illustrations: ["../../public/images/kx-grandioseplot.png"],
		rating: [""],
		tags: ["combo", "discard", "player damage"],
		comments: ["Good in the aggressive deck but better in the card draw combo build. - JM"]
	},
	{
		name: "Deep Pockets",
		character: "Knox",
		type: "Feat",
		utilityValues: [""],
		text: "Draw 7 cards.",
		flavor: [""],
		illustrations: ["../../public/images/kx-deeppockets.png"],
		rating: [""],
		tags: ["combo", "build-around", "card draw"],
		comments: ["You can't do this with an overly aggressive deck because you'll be dead by turn five. - JM"]
	},
	{
		name: "Distracting Insults",
		character: "Knox",
		type: "Feat",
		utilityValues: [""],
		text: "Skip your discard phase this turn.",
		flavor: [""],
		illustrations: ["../../public/images/kx-cruelinsults.png"],
		rating: [""],
		tags: ["versatile", "card draw", "build-around"],
		comments: ["Cool card. Having this on command makes sure your next turn is big. - JM"]
	},
	{
		name: "Pile On",
		character: "Knox",
		type: "Feat",
		utilityValues: [""],
		text: "Whenever you play an Action this turn, deal 2 damage to each opponent.",
		flavor: [""],
		illustrations: ["../../public/images/kx-theonewhoisknox.png"],
		rating: [""],
		tags: ["aggressive", "combo", "player damage"],
		comments: ["Cheap Shot and Violent Strike help to make sure you get 8-10 damage off of this. - JM"]
	},
	{
		name: "Reckless Heist",
		character: "Knox",
		type: "Feat",
		utilityValues: [""],
		text: "Destroy each of your Utilities with Minion. Deal 3 damage to each opponent for each Utility destroyed.",
		flavor: [""],
		illustrations: ["../../public/images/kx-recklessheist.png"],
		rating: [""],
		tags: ["aggressive", "minion", "player damage"],
		comments: ["Having up to nine damage on hand is nothing to ignore. Forces players into defensive positions. - JM"]
	},
	{
		name: "A Safe Position",
		character: "Obscurity",
		type: "Utility",
		utilityValues: ["3","0","3"],
		text: "When you play this, look at the top two cards of your deck. You may draw one and discard the other.",
		flavor: ["It's getting hard to find things in this jacket, let's see...I've got a DNA scanner, a skeletop key and...Yes! A granola bar!"],
		illustrations: ["../../public/images/ob-whatafind.png"],
		rating: [""],
		tags: ["defensive", "card draw"],
		comments: ["Seeing two cards is big game. - JM"]
	},
	{
		name: "Case Closed!",
		character: "Obscurity",
		type: "Utility",
		utilityValues: ["4","0","0"],
		text: "At the end of your turn, if all of your other Utilities are face-down, deal 5 damage to each opponent.",
		flavor: ["One more win for the good guys!"],
		illustrations: ["../../public/images/ob-caseclosed.png"],
		rating: [""],
		tags: ["combo", "player damage", "vanish"],
		comments: ["This requires good timing because vanish decks want to be flipping constantly. - JM"]
	},
	{
		name: "Casing The Scene",
		character: "Obscurity",
		type: "Action",
		utilityValues: [""],
		text: "Draw 2 cards. OR Draw 6 cards.",
		flavor: ["Oh geez, I hope he doesn't see me."],
		illustrations: ["../../public/images/ob-casingthescene.png"],
		rating: [""],
		tags: ["versatile", "card draw"],
		comments: ["Drawing six isn't as good as it seems. It's a big chunk of health. Nice card though. - JM"]
	},
	{
		name: "Checking My Pockets",
		character: "Obscurity",
		type: "Action",
		utilityValues: [""],
		text: "Draw 2 cards. OR Vanish two target Gadgets.",
		flavor: ["A quarter...a granola bar..."],
		illustrations: ["../../public/images/ob-checkingmypockets.png"],
		rating: [""],
		tags: ["versatile", "vanish", "card draw"],
		comments: ["Two vanish triggers is a big deal. You won't want the card draw all too often. - JM"]
	},
	{
		name: "Crack Shot",
		character: "Obscurity",
		type: "Action",
		utilityValues: [""],
		text: "2 damage to any target. OR Vanish target Gadget.",
		flavor: ["Stand back, I've got this one."],
		illustrations: ["../../public/images/ob-whatafind.png"],
		rating: [""],
		tags: ["aggressive", "player damage", "utility damage", "vanish"],
		comments: ["Obscurity struggles with damage so keep this one close. - JM"]
	},
	{
		name: "Decisions, Decisions...",
		character: "Obscurity",
		type: "Action",
		utilityValues: [""],
		text: "Play the top card of your deck OR your discard pile for free.",
		flavor: ["Brownie or cake? Pie? Baklava?"],
		illustrations: ["../../public/images/ob-decisionsdecisions.png"],
		rating: [""],
		tags: ["card draw", "combo" ],
		comments: ["Great in the vanish deck hungry for triggers, but just fine otherwise. - JM"]
	},
	{
		name: "Drop From The Ceiling",
		character: "Obscurity",
		type: "Action",
		utilityValues: [""],
		text: "Deal 4 damage to target Utility. OR Vanish target Gadget.",
		flavor: ["Here goes nothing..."],
		illustrations: ["../../public/images/ob-pounce.png"],
		rating: [""],
		tags: ["aggressive", "utility damage", "vanish"],
		comments: ["Sometimes you just need to get rid of something. - JM"]
	},
	{
		name: "First Aid Microkit",
		character: "Obscurity",
		type: "Utility",
		utilityValues: ["4","0","0"],
		text: "Gadget. When you Vanish this, Heal 2.",
		flavor: ["It works, I promise! I use it almost every day."],
		illustrations: ["../../public/images/ob-firstaidkit.png"],
		rating: [""],
		tags: ["defensive", "vanish", "healing"],
		comments: ["Use this to cycle your vanish cards back into your deck. - JM"]
	},
	{
		name: "Flashbangs",
		character: "Obscurity",
		type: "Utility",
		utilityValues: ["6","0","0"],
		text: "Gadget. If this is the third Gadget you've turned upside-down this turn, take an extra turn after this one.",
		flavor: ["Cover your ears everybody! Sorry! Sorry!"],
		illustrations: ["../../public/images/ob-whatafind.png"],
		rating: [""],
		tags: ["combo", "vanish", "disruption"],
		comments: ["Hard to work, but definitely worth the effort. Decisions, Decisions helps. - JM"]
	},
	{
		name: "Giving My All",
		character: "Obscurity",
		type: "Utility",
		utilityValues: ["4","0","4"],
		text: "Replace the word OR with the word AND on all of your cards.",
		flavor: ["You picked the wrong time, buddy. I'm missing lunch."],
		illustrations: ["../../public/images/ob-illnevergiveup.png"],
		rating: [""],
		tags: ["combo", "build-around"],
		comments: ["If you've got a lot of modal cards, this is absolutely worth the effort of building around. - JM"]
	},
	{
		name: "High Anxiety",
		character: "Obscurity",
		type: "Utility",
		utilityValues: ["3","0","0"],
		text: "Whenever you play a Gadget, you may Vanish it.",
		flavor: ["I keep fidgeting with this thing...AAAAH!"],
		illustrations: ["../../public/images/ob-highanxiety.png"],
		rating: [""],
		tags: ["combo", "vanish"],
		comments: ["Works well with aggressive gadgets and poorly with combo pieces. - JM"]
	},
	{
		name: "Lefts & Rights",
		character: "Obscurity",
		type: "Action",
		utilityValues: [""],
		text: "Deal 2 damage to any target, then deal 2 damage to a different target.",
		flavor: ["Please give up. My hand hurts."],
		illustrations: ["../../public/images/ob-leftsandrights.png"],
		rating: [""],
		tags: ["aggressive", "player damage", "utility damage", "versatile"],
		comments: ["Can really keep an aggressive player off their feet. Doesn't combo well with anything. - JM"]
	},
	{
		name: "Magnetic Handcuffs",
		character: "Obscurity",
		type: "Utility",
		utilityValues: ["1","2","0"],
		text: "Gadget. When you Vanish this, return target Utility to its owner's hand.",
		flavor: ["I don't think you'll be firing that thing anytime soon."],
		illustrations: ["../../public/images/ob-magnetichandcuffs.png"],
		rating: [""],
		tags: ["aggressive", "utility damage", "vanish"],
		comments: ["This into player damage gets rid of things permanently. - JM"]
	},
	{
		name: "Mid-Day Snack",
		character: "Obscurity",
		type: "Action",
		utilityValues: [""],
		text: "Heal 2. Draw a card.",
		flavor: ["Whew. Long day. Anybody hungry?"],
		illustrations: ["../../public/images/ob-whatafind.png"],
		rating: [""],
		tags: ["defensive", "card draw", "healing"],
		comments: ["Not playable in every deck, but buys you a turn or so. - JM"]
	},
	{
		name: "Pastel Pistol",
		character: "Obscurity",
		type: "Utility",
		utilityValues: ["3","2","0"],
		text: "Gadget. When you Vanish this, deal 2 damage to target opponent.",
		flavor: ["Hate to do this, but..."],
		illustrations: ["../../public/images/ob-pastelpistol.png"],
		rating: [""],
		tags: ["aggressive", "combo", "player damage", "vanish"],
		comments: ["Centerpiece of the vanish deck. Keep it safe. - JM"]
	},
	{
		name: "Police Band Radio",
		character: "Obscurity",
		type: "Utility",
		utilityValues: ["2","2","0"],
		text: "Gadget. At the end of your turn, Heal 2 OR draw a card.",
		flavor: ["Obscurity! This is Detective Wolf Cop! Stop hiding and answer your radio!"],
		illustrations: ["../../public/images/ob-policeband.png"],
		rating: [""],
		tags: ["versatile", "card draw", "healing"],
		comments: ["Doesn't work face-down, but plays well with combo decks."]
	},
	{
		name: "Static Grenade",
		character: "Obscurity",
		type: "Utility",
		utilityValues: ["2","2","0"],
		text: "Gadget. When you Vanish this, deal 1 damage to each opponent and each of their Utilities.",
		flavor: ["It might be non-lethal, but it is really hecking loud."],
		illustrations: ["../../public/images/ob-staticgrenades.png"],
		rating: [""],
		tags: ["aggressive", "combo", "vanish"],
		comments: ["This deals a lot of damage over the course of the game if kept hidden. - JM"]
	},
	{
		name: "Trusting My Gut",
		character: "Obscurity",
		type: "Utility",
		utilityValues: ["5","0","0"],
		text: "Whenever you play a card with the word OR in the text, Vanish target Gadget.",
		flavor: ["Hold up...I have an idea."],
		illustrations: ["../../public/images/ob-whatafind.png"],
		rating: [""],
		tags: ["combo", "vanish"],
		comments: ["You can go down the modal path and basically play a detective deck. Fun combo piece. - JM"]
	},
	{
		name: "Twiddling My Thumbs",
		character: "Obscurity",
		type: "Utility",
		utilityValues: [""],
		text: "Draw 2 cards. OR Heal 3.",
		flavor: ["Oh boy...I might need a second here."],
		illustrations: ["../../public/images/ob-bidingmytime.png"],
		rating: [""],
		tags: ["defensive", "card draw", "healing"],
		comments: ["You have a lot of defensive options, but balancing healing and card draw can buy you turns. - JM"]
	},
	{
		name: "Vibro-Knuckle Dusters",
		character: "Obscurity",
		type: "Utility",
		utilityValues: ["1","3","0"],
		text: "Gadget. When you Vanish this, play the top card of your deck.",
		flavor: ["I've always got something neat up my sleeve..."],
		illustrations: ["../../public/images/ob-vibroknuckledusters.png"],
		rating: [""],
		tags: ["combo", "card draw", "aggressive", "vanish"],
		comments: ["Yeah the ability is good, but 3 fight is nothing to ignore. - JM"]
	},
	{
		name: "X-Ray Spex",
		character: "Obscurity",
		type: "Utility",
		utilityValues: ["5","0","0"],
		text: "Gadget. When you Vanish this, you may play an Action from your hand for free.",
		flavor: [""],
		illustrations: ["../../public/images/ob-completelyinvisible.png"],
		rating: [""],
		tags: ["versatile", "combo", "vanish"],
		comments: ["This thing isn't great but it never goes away. - JM"]
	},	
	{
		name: "Rubber Maiden",
		character: "Obscurity",
		type: "Crossover",
		utilityValues: ["3","3","0"],
		text: "Whenever this is dealt damage, deal 3 damage to each opponent.",
		flavor: ["When It Bounces Off Her, She Sticks It To You"],
		illustrations: ["../../public/images/cross-rubbermaiden.png"],
		rating: [""],
		tags: ["crossover", "aggressive", "player damage", "utility damage", "versatile"],
		comments: ["Fits in any deck that wants to be beating down. Scary. - JM"]
	},
	{
		name: "Det. Wolf Cop",
		character: "Obscurity",
		type: "Crossover",
		utilityValues: ["3","1","3"],
		text: "Your other Utilities can't be destroyed.",
		flavor: ["Fighting Evil By Moonlight"],
		illustrations: ["../../public/images/cross-detwolfcop.png"],
		rating: [""],
		tags: ["crossover", "defensive", "build-around"],
		comments: ["Doesn't stay alive, but definitely draws attention. - JM"]
	},
	{
		name: "Suprise!",
		character: "Obscurity",
		type: "Feat",
		utilityValues: [""],
		text: "Replace the word OR with the word AND on all of your cards this turn.",
		flavor: [""],
		illustrations: ["../../public/images/ob-emerge.png"],
		rating: [""],
		tags: ["combo", "versatile"],
		comments: ["Works with a lot of cards in every deck. Very playable in the vanish deck too. - JM"]
	},
	{
		name: "Calm Down",
		character: "Obscurity",
		type: "Feat",
		utilityValues: [""],
		text: "Each player discards their hand.",
		flavor: [""],
		illustrations: ["../../public/images/ob-calmdown.png"],
		rating: [""],
		tags: ["defensive", "disruption"],
		comments: ["Obscurity needs to bide time in order to win. This helps. - JM"]
	},
	{
		name: "Quick Draw",
		character: "Obscurity",
		type: "Feat",
		utilityValues: [""],
		text: "Play a Gadget from your hand for free, then Vanish it.",
		flavor: [""],
		illustrations: ["../../public/images/ob-quickdraw.png"],
		rating: [""],
		tags: ["aggressive", "combo", "vanish"],
		comments: ["This can get an important vanish trigger or complete a combo. This speeds things up. - JM"]
	},
	{
		name: "Piston Kicks",
		character: "Obscurity",
		type: "Feat",
		utilityValues: [""],
		text: "Deal 2 damage to three different targets.",
		flavor: [""],
		illustrations: ["../../public/images/ob-pistonkicks.png"],
		rating: [""],
		tags: ["versatile", "aggressive", "player damage", "utility damage"],
		comments: ["Hard to follow up on, but can definitely shut down fragile strategies early. - JM"]
	},
	{
		name: "Empty Pockets",
		character: "Obscurity",
		type: "Feat",
		utilityValues: [""],
		text: "Vanish each of your Gadgets.",
		flavor: [""],
		illustrations: ["../../public/images/ob-subdue.png"],
		rating: [""],
		tags: ["aggressive", "combo", "vanish", "build-around"],
		comments: ["If you can set this up, it can finish out a game early. - JM"]
	},
	{
		name: "Bank Account Numbers",
		character: "Query",
		type: "Utility",
		utilityValues: ["3","3","0"],
		text: "Whenever this damages an opponent, that player discards a card.",
		flavor: ["Take one step closer and you'll be bankrupt."],
		illustrations: ["../../public/images/qu-bankaccountnumbers.png"],
		rating: [""],
		tags: ["aggressive", "disruption"],
		comments: ["Isn't fancy but gets the job done. - JM"]
	},
	{
		name: "Connecting The Dots...",
		character: "Query",
		type: "Action",
		utilityValues: [""],
		text: "1 damage to any target. Play the top card of target opponent's deck for free.",
		flavor: ["Only three cypher layers? Do better."],
		illustrations: ["../../public/images/qu-connectthedots.png"],
		rating: [""],
		tags: ["combo", "card draw"],
		comments: ["The damage rarely matters, but can finish off a Utility. - JM"]
	},
	{
		name: "Counterfeit Faces",
		character: "Query",
		type: "Utility",
		utilityValues: ["5","1","0"],
		text: "Whenever this deals damage to an opponent, Heal 1.",
		flavor: ["How could I? Easily. I contain multitudes."],
		illustrations: ["../../public/images/qu-stolenface.png"],
		rating: [""],
		tags: ["defensive", "versatile", "healing"],
		comments: ["If you don't plan to be using a lot of Utilities this is a great early play. - JM"]
	},
	{
		name: "Dead Drop",
		character: "Query",
		type: "Utility",
		utilityValues: ["4","0","0"],
		text: "At the beginning of your turn, you may discard a card. If you do, play the top card of target opponent's deck.",
		flavor: ["I've got safehouses everywhere. Come with me."],
		illustrations: ["../../public/images/qu-stolenface.png"],
		rating: [""],
		tags: ["defensive", "combo", "card draw", "discard"],
		comments: ["This effect is about 50/50 but gets better in multiples. - JM"]
	},
	{
		name: "Dezinformatsiya",
		character: "Query",
		type: "Utility",
		utilityValues: ["2","3","2"],
		text: "At the beginning of your turn, you may look at the top card of each player's deck.",
		flavor: ["What's real and what's not? Who cares?"],
		illustrations: ["../../public/images/qu-dezinformatsiya.png"],
		rating: [""],
		tags: ["aggressive", "armor", "disruption"],
		comments: ["Great way to set up your stolen cards. Hits hard too. - JM"]
	},
	{
		name: "Experimental Serum",
		character: "Query",
		type: "Utility",
		utilityValues: ["1","1","0"],
		text: "When you play this Heal 1 for each card in your hand.",
		flavor: ["Down the hatch, I suppose."],
		illustrations: ["../../public/images/qu-experimentalserum.png"],
		rating: [""],
		tags: ["defensive", "versatile", "healing"],
		comments: ["Easy to get 4 or 5 out of it and works wells with Psyops. - JM"]
	},
	{
		name: "False Flag Attacks",
		character: "Query",
		type: "Action",
		utilityValues: [""],
		text: "2 damage to any target. Spy.",
		flavor: ["Who would do such a thing?"],
		illustrations: ["../../public/images/qu-falseflagattacks.png"],
		rating: [""],
		tags: ["aggressive", "player damage", "aggressive damage", "versatile", "spy"],
		comments: ["Great way to dig yourself out of a hole. - JM"]
	},
	{
		name: "Gathering Intelligence",
		character: "Query",
		type: "Action",
		utilityValues: [""],
		text: "Spy. Draw a card.",
		flavor: ["So many fingerprints. So little time."],
		illustrations: ["../../public/images/qu-gatheringintel.png"],
		rating: [""],
		tags: ["defensive", "card draw", "disruption", "combo", "spy"],
		comments: ["Great in a combo or thief deck. - JM"]
	},
	{
		name: "Honeypot Trap",
		character: "Query",
		type: "Utility",
		utilityValues: ["3","1","0"],
		text: "When this is destroyed, you may play the top card of target player's deck.",
		flavor: ["Seducing some dullard is like a day off for me."],
		illustrations: ["../../public/images/qu-honeypottrap.png"],
		rating: [""],
		tags: ["defensive", "disruption", "card draw"],
		comments: ["This is extremely good as a live threat. Replace it with another Utility to guarantee the trigger. - JM"]
	},
	{
		name: "Information Leaks",
		character: "Query",
		type: "Utility",
		utilityValues: ["1","2","0"],
		text: "When this deals damage to an opponent, you may play the top card of your deck for free.",
		flavor: ["Are you hiding from the world? I'm still listening in."],
		illustrations: ["../../public/images/qu-informationleak.png"],
		rating: [""],
		tags: ["aggressive", "disruption", "card draw"],
		comments: ["Hit them fast and often. - JM"]
	},
	{
		name: "Lightning Bug",
		character: "Query",
		type: "Utility",
		utilityValues: ["3","2","0"],
		text: "Whenever this deals damage to an opponent, you may Spy on them.",
		flavor: ["I didn't hide a thing. I can't wait until they find it."],
		illustrations: ["../../public/images/qu-lightningbug.png"],
		rating: [""],
		tags: ["aggressive", "disrution", "spy"],
		comments: ["Repeated spy triggers can bury good cards away from your opponent. - JM"]
	},
	{
		name: "Listening In...",
		character: "Query",
		type: "Action",
		utilityValues: [""],
		text: "Spy, then deal 1 damage to any target, then Spy again.",
		flavor: ["John, whose voice is that? John? John?!"],
		illustrations: ["../../public/images/qu-listeningin.png"],
		rating: [""],
		tags: ["versatile", "disruption", "spy"],
		comments: ["Combine the first two effects to get rid of a nasty card in your opponent's deck. - JM"]
	},	
	{
		name: "Music Box",
		character: "Query",
		type: "Utility",
		utilityValues: ["3","0","2"],
		text: "At the beginning and end of your turn, Heal 1.",
		flavor: ["The gears will keep spinning long after I'm gone."],
		illustrations: ["../../public/images/qu-musicbox.png"],
		rating: [""],
		tags: ["defensive", "healing", "armor"],
		comments: ["Kill this thing on sight. - JM"]
	},
	{
		name: "Paranoid Delusions",
		character: "Query",
		type: "Utility",
		utilityValues: ["5","0","0"],
		text: "At the beginning of your turn, you may discard a card. If you do, exchange this with another Utility in play.",
		flavor: ["Have trouble seeing things clearly? Let me help."],
		illustrations: ["../../public/images/qu-induceparanoia.png"],
		rating: [""],
		tags: ["disruption", "aggressive", "discard"],
		comments: ["They can feed it cards or let you steal their best Utility. Excellent card. - JM"]
	},
	{
		name: "Psyop Campaign",
		character: "Query",
		type: "Utility",
		utilityValues: ["3","0","2"],
		text: "Your other Utilities get +1 Fight.",
		flavor: ["Once you figure out what's going on, it'll be too late."],
		illustrations: ["../../public/images/qu-psyopcampaign.png"],
		rating: [""],
		tags: ["aggressive", "fight". "armor"],
		comments: ["Query has some of the most aggressive Utiilities in the game and this turns them up a notch. - JM"]
	},
	{
		name: "Revenge Plot",
		character: "Query",
		type: "Action",
		utilityValues: [""],
		text: "Look at the top five cards of your deck. You may draw one of these cards, then return the rest in any order.",
		flavor: ["Patience. Above all else, patience."],
		illustrations: ["../../public/images/qu-revengeplot.png"],
		rating: [""],
		tags: ["versatile", "card draw"],
		comments: ["Great 30th card. Always finds you something. - JM"]
	},
	{
		name: "Sabotage!",
		character: "Query",
		type: "Utility",
		utilityValues: ["2","0","0"],
		text: "Whenever a card is playing from the top of a player's deck, destroy this and 3 damage to each opponent.",
		flavor: ["Nothing you own is safe. Tread lightly."],
		illustrations: ["../../public/images/qu-sabotage.png"],
		rating: [""],
		tags: ["aggressive", "combo", "player damage"],
		comments: ["Query isn't always aggro, but this sure does help. - JM"]
	},
	{
		name: "Sanitize",
		character: "Query",
		type: "Action",
		utilityValues: [""],
		text: "2 damage to target Utility. Heal 2.",
		flavor: ["Not working? Burn it to the ground."],
		illustrations: ["../../public/images/qu-sanitize.png"],
		rating: [""],
		tags: ["versatile", "utility damage", "healing"],
		comments: ["Not great damage, but you'll take it if you need it. - JM"]
	},
	{
		name: "Savate Kick",
		character: "Query",
		type: "Action",
		utilityValues: [""],
		text: "Deal 3 damage to any target.",
		flavor: ["I'm taking it all. Including your teeth."],
		illustrations: ["../../public/images/qu-savatekick.png"],
		rating: [""],
		tags: ["versatile", "player damage", "utility damage"],
		comments: ["Handles most problems. Always run this. - JM"]
	},	
	{
		name: "Seizing Assets",
		character: "Query",
		type: "Action",
		utilityValues: [""],
		text: "Reveal the top card of target opponent's deck. You may play this card for free or discard it. Your choice.",
		flavor: ["Anything owned can be taken."],
		illustrations: ["../../public/images/qu-seizingassets.png"],
		rating: [""],
		tags: ["defensive", "disruption", "card draw", "combo"],
		comments: ["If you need to steal something, this isn't a bad option. - JM"]
	},	
	{
		name: "Untimely Data Breach",
		character: "Query",
		type: "Action",
		utilityValues: [""],
		text: "Heal 2. Play the top card of your deck for free.",
		flavor: ["Are you still struggling? I'm busy."],
		illustrations: ["../../public/images/qu-untimelydatabreach.png"],
		rating: [""],
		tags: ["defensive", "healing", "card draw"],
		comments: ["Sometimes you'll be stuck playing a lot of healing cards to fight back against big player damage. This works. - JM"]
	},
	{
		name: "Blaire Eva Solomon",
		character: "Query",
		type: "Crossover",
		utilityValues: ["3","2","3"],
		text: "At the end of your turn, you may shuffle this into your deck, If you do, draw 2 cards afterwards.",
		flavor: ["Vagrant Shaman Reeking Of Cigarettes"],
		illustrations: ["../../public/images/cross-blaireevasolomon.png"],
		rating: [""],
		tags: ["crossover", "defensive", "armor", "card draw"],
		comments: [""]
	},
	{
		name: "Dr. Doodad",
		character: "Query",
		type: "Crossover",
		utilityValues: ["1","3","3"],
		text: "Whenever this deals damage to an opponent, draw a card and Heal 2.",
		flavor: ["Ridding The World Of Disease & Large Sandwiches"],
		illustrations: ["../../public/images/cross-drdoodad.png"],
		rating: [""],
		tags: ["crossover", "aggressive", "card draw", "healing"],
		comments: ["Even one good hit is enough to play this card. Combo decks like it.- JM"]
	},
	{
		name: "If Not Now, When?",
		character: "Query",
		type: "Feat",
		utilityValues: [""],
		text: "Look at the top card of each player's deck. You may play one of those cards for free.",
		flavor: [""],
		illustrations: ["../../public/images/qu-ifnotnowwhen.png"],
		rating: [""],
		tags: ["card draw", "aggressive", "feat"],
		comments: ["Very strong turn one play. - JM"]
	},
	{
		name: "What Do We Have Here?",
		character: "Query",
		type: "Feat",
		utilityValues: [""],
		text: "Each opponent reveals their hand. You may play a Utility revealed this way for free.",
		flavor: [""],
		illustrations: ["../../public/images/qu-whatdowehavehere.png"],
		rating: [""],
		tags: ["versatile", "card draw", "disruption", "discard"],
		comments: ["This works quite well in almost any build. Good when you don't know what to expect. - JM"]
	},
	{
		name: "Where Were You Going?",
		character: "Query",
		type: "Feat",
		utilityValues: [""],
		text: "Deal 3 damage to target Utility and target opponent.",
		flavor: [""],
		illustrations: ["../../public/images/qu-wherewereyougoing.png"],
		rating: [""],
		tags: ["aggressive", "player damage", "utility damage"],
		comments: ["Not quite as good against defensive decks, but knocks most things out of the way. - JM"]
	},
	{
		name: "Who Am I?",
		character: "Query",
		type: "Feat",
		utilityValues: [""],
		text: "Target opponent sorts the top three cards of your deck into two piles. Draw one and discard the other.",
		flavor: [""],
		illustrations: ["../../public/images/qu-whoami.png"],
		rating: [""],
		tags: ["versatile", "card draw"],
		comments: ["Works well with spy and refills your hand. - JM"]
	},
	{
		name: "Why Bother?",
		character: "Query",
		type: "Feat",
		utilityValues: [""],
		text: "Heal 3. Look at the top card of each player's deck.",
		flavor: [""],
		illustrations: ["../../public/images/qu-whybother.png"],
		rating: [""],
		tags: ["defensive", "combo", "healing"],
		comments: ["Buys a turn and sets up a good steal. - JM"]
	},
	{
		name: "Adrenaline",
		character: "Sportsman",
		type: "Crossover",
		utilityValues: ["3","2","0"],
		text: "At the beginning of your turn, you may discard 3 cards. If you do, this gets +4 Fight this turn.",
		flavor: ["Feels Nothing And Hates Everything - Especially You"],
		illustrations: ["../../public/images/cross-adrenaline.png"],
		rating: [""],
		tags: ["crossover", "aggressive", "discard", "fight"],
		comments: ["If you keep a full hand, this guy's base stats are good enough to consider. - JM"]
	},
	{
		name: "Albedo",
		character: "Sportsman",
		type: "Crossover",
		utilityValues: ["3","2","0"],
		text: "Whenever this deals damage to a player, it gains that much Armor.",
		flavor: ["His Aloof Cruelty Is Reflected In His Bank Account"],
		illustrations: ["../../public/images/cross-albedo.png"],
		rating: [""],
		tags: ["crossover", "defensive", "combo", "armor"],
		comments: ["Great way to annoy the opponent, especially with multiple hits. - JM"]
	},
	{
		name: "Chance",
		character: "Generation Justice",
		type: "Crossover",
		utilityValues: ["4","1","0"],
		text: "At the end of your turn, flip a coin. If it is heads, 2 damage to any target and Heal 2.",
		flavor: ["Somehow Things Just Keep Going His Way..."],
		illustrations: ["../../public/images/cross-chance.png"],
		rating: [""],
		tags: ["crossover", "versatile", "player damage", "opponent damage", "healing"],
		comments: ["Quite an all-star if you manage to get lucky. - JM"]
	},
	{
		name: "Death Boy & Goobo",
		character: "Generation Justice",
		type: "Crossover",
		utilityValues: ["3","2","2"],
		text: "At the beginning of your turn, you may return this and the top card of your discard pile to your hand.",
		flavor: ["Adolescent God Of Death & His Slime Golem Son"],
		illustrations: ["../../public/images/cross-deathboyandgoobo.png"],
		rating: [""],
		tags: ["crossover", "combo", "defensive", "card draw"],
		comments: ["Definitely helps keep a combo engine running. - JM"]
	},
	{
		name: "Fiona",
		character: "Generation Justice",
		type: "Crossover",
		utilityValues: ["3","3","0"],
		text: "Fiona cant fight the turn she is played. Whenever this deals damage, it gets +1 Armor",
		flavor: ["Hot-Blooded Demigod With Something To Prove"],
		illustrations: ["../../public/images/cross-fiona.png"],
		rating: [""],
		tags: ["crossover", "aggressive", "armor", "armor"],
		comments: ["She can't stay around too long until she takes over a game. - JM"]
	},
	{
		name: "Graverobber",
		character: "Silicon Artist",
		type: "Crossover",
		utilityValues: ["3","1","2"],
		text: "When you play this, you may play the top card of your discard pile for free if it is a Utility.",
		flavor: ["Collects Dead Historical Figures. Ick."],
		illustrations: ["../../public/images/cross-graverobber.png"],
		rating: [""],
		tags: ["crossover", "combo", "card draw"],
		comments: ["This card brings important stuff back to life, especially if you manage to wait a turn or two. - JM"]
	},
	{
		name: "Iron Justice",
		character: "Wayfarer",
		type: "Crossover",
		utilityValues: ["4","2","0"],
		text: "You can't lose the game.",
		flavor: ["The Invincible Guardian of Steel City"],
		illustrations: ["../../public/images/cross-ironjustice.png"],
		rating: [""],
		tags: ["crossover", "defensive", "disruption", "build-around", "combo"],
		comments: ["Yeah this card is good, but much better if your deck is filled with fragile combos. - JM"]
	},
	{
		name: "Lightspeed",
		character: "Ladybug & Ze Flying Squirrel",
		type: "Crossover",
		utilityValues: ["4","2","0"],
		text: "At the beginning of your turn, draw 2 cards then discard 2 cards.",
		flavor: ["The World's Fastest Walking Advertisement"],
		illustrations: ["../../public/images/cross-lightspeed.png"],
		rating: [""],
		tags: ["crossover", "aggressive", "card draw", "discard"],
		comments: ["Don't let him stick around forever, you can't turn him off. - JM"]
	},
	{
		name: "Puzzle King",
		character: "Silicon Artist",
		type: "Crossover",
		utilityValues: ["3","1","2"],
		text: "When you play this, play the top card of your deck for free.",
		flavor: ["The Magnificent Monarch Of Mindbenders!"],
		illustrations: ["../../public/images/cross-puzzleking.png"],
		rating: [""],
		tags: ["crossover", "defensive", "card draw"],
		comments: ["Isn't too impactful alone, but is great when played multiple times. - JM"]
	},
	{
		name: "Sophia",
		character: "Generation Justice",
		type: "Crossover",
		utilityValues: ["3","0","2"],
		text: "This gets +1 Fight for each Crossover in play.",
		flavor: ["She And Her Six Ghost Hamsters Are New In Town"],
		illustrations: ["../../public/images/cross-sophia.png"],
		rating: [""],
		tags: ["crossover", "aggressive", "build-around"],
		comments: ["If you can secure Crossovers, this gets out of control quickly. Great in multiplayer. - JM"]
	},
	{
		name: "Static",
		character: "Ladybug & Ze Flying Squirrel",
		type: "Crossover",
		utilityValues: ["1","3","0"],
		text: "At the end of your turn, 2 damage to target opponent.",
		flavor: ["Shocking Bank Robber With A Lethal Touch"],
		illustrations: ["../../public/images/cross-static.png"],
		rating: [""],
		tags: ["aggressive", "player damage"],
		comments: ["Can't be left alone. She's five per turn by herself. - JM"]
	},	
	{
		name: "The Evangelist",
		character: "Wayfarer",
		type: "Crossover",
		utilityValues: ["5","0","0"],
		text: "At the end of your turn, discard 3 cards. Search your deck for a Crossover and put it into your hand. Shuffle afterwards.",
		flavor: ["Leading Lambs To The Slaughter"],
		illustrations: ["../../public/images/cross-theevangelist.png"],
		rating: [""],
		tags: ["combo", "discard", "card draw", "build-around"],
		comments: ["Deal with the devil. Make sure whatever you get is worth the steep cost. - JM"]
	},
]